import type { WidgetConfig } from '../types/widget';

export const DC_COMPANIES_SEED = [
  {
    id: 'dc-001',
    name: 'NexGen Data Centres Ltd',
    type: 'developer',
    location: 'Manchester, UK',
    website: 'https://nexgendatacentres.co.uk',
    stage: 'target',
    first_seen: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['new-build', 'hyperscale', 'north-west'],
    annual_revenue: null,
    notes: 'Planning application submitted for 48MW campus in MediaCityUK area',
  },
  {
    id: 'dc-002',
    name: 'EdgeCore European Holdings',
    type: 'operator',
    location: 'Dublin, Ireland',
    website: 'https://edgecore.com',
    stage: 'lead',
    first_seen: new Date(Date.now() - 22 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['colocation', 'expansion', 'europe'],
    annual_revenue: 85000000,
    notes: 'Expanding Dublin campus - Phase 3 seeking MEP refurb contractor',
  },
  {
    id: 'dc-003',
    name: 'GridPoint Infrastructure PLC',
    type: 'developer',
    location: 'Slough, UK',
    website: 'https://gridpoint.io',
    stage: 'target',
    first_seen: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['new-build', 'power-hungry', 'london-fringe'],
    annual_revenue: null,
    notes: 'Grid connection secured for 60MW site near M4 corridor',
  },
  {
    id: 'dc-004',
    name: 'Titan Hosting Group',
    type: 'colo',
    location: 'Leeds, UK',
    website: 'https://titanhosting.co.uk',
    stage: 'lead',
    first_seen: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['colocation', 'refurbishment', 'yorkshire'],
    annual_revenue: 12000000,
    notes: 'Legacy facility requiring full MEP upgrade - Tier III target',
  },
  {
    id: 'dc-005',
    name: 'Axiom Cloud Spaces Ltd',
    type: 'hyperscaler',
    location: 'London, UK',
    website: 'https://axiomcloud.com',
    stage: 'target',
    first_seen: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['hyperscale', 'new-build', 'southeast'],
    annual_revenue: 220000000,
    notes: 'Acquired 40-acre brownfield site in Thurrock for potential 200MW campus',
  },
  {
    id: 'dc-006',
    name: 'Polar Data Facilities Nordic',
    type: 'developer',
    location: 'Helsinki, Finland',
    website: 'https://polardata.fi',
    stage: 'target',
    first_seen: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['new-build', 'green-energy', 'nordic'],
    annual_revenue: null,
    notes: 'Seeking UK-based MEP specialist for greenfield Scandinavian deployment',
  },
  {
    id: 'dc-007',
    name: 'Vault Networks Ltd',
    type: 'operator',
    location: 'Birmingham, UK',
    website: 'https://vaultnetworks.co.uk',
    stage: 'lead',
    first_seen: new Date(Date.now() - 67 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['colocation', 'midlands', 'ai-ready'],
    annual_revenue: 34000000,
    notes: 'Upgrading power density to support GPU cluster tenants - 5MW expansion',
  },
  {
    id: 'dc-008',
    name: 'ClearPath Datacentre Solutions',
    type: 'enterprise',
    location: 'Bristol, UK',
    website: 'https://clearpathdcs.com',
    stage: 'target',
    first_seen: new Date(Date.now() - 29 * 24 * 60 * 60 * 1000).toISOString(),
    tags: ['enterprise', 'southwest', 'refurbishment'],
    annual_revenue: 8000000,
    notes: 'Owner-operator seeking full Tier II to Tier III upgrade path',
  },
];

export const DC_NEWS_SEED = [
  {
    id: 'news-001',
    company: 'NexGen Data Centres Ltd',
    category: 'expansion',
    headline: 'NexGen submits planning for 48MW MediaCity campus',
    summary: 'Planning application submitted to Salford City Council for a new 48MW hyperscale data centre development at MediaCityUK. Construction expected to begin Q3 2025 pending approval.',
    source: 'Data Centre Magazine',
    url: 'https://datacentremagazine.com',
    published_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'news-002',
    company: 'EdgeCore European Holdings',
    category: 'expansion',
    headline: 'EdgeCore breaks ground on Dublin Phase 3',
    summary: 'EdgeCore European Holdings has commenced Phase 3 of its Dublin campus, adding 28MW of IT load. The project is expected to cost €180M and complete by mid-2026.',
    source: 'DCD',
    url: 'https://datacenterdynamics.com',
    published_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'news-003',
    company: 'GridPoint Infrastructure PLC',
    category: 'funding',
    headline: 'GridPoint secures £200M Series B for M4 corridor campus',
    summary: 'GridPoint Infrastructure has completed a £200M Series B funding round led by infrastructure fund Stonepeak. Capital will fund the 60MW Slough facility with first shells ready Q4 2025.',
    source: 'This is Money',
    url: 'https://thisismoney.co.uk',
    published_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'news-004',
    company: 'Axiom Cloud Spaces Ltd',
    category: 'expansion',
    headline: 'Axiom acquires Thurrock brownfield for 200MW hyperscale campus',
    summary: 'Axiom Cloud Spaces has purchased a 40-acre former industrial site in Thurrock, Essex, with plans for a 200MW hyperscale campus targeting AI workload tenants. JLL acted as acquisition advisor.',
    source: 'CoStar',
    url: 'https://costar.com',
    published_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'news-005',
    company: 'Vault Networks Ltd',
    category: 'technology',
    headline: 'Vault Networks upgrades Birmingham campus for GPU-dense AI workloads',
    summary: 'Vault Networks is investing £12M in power density upgrades to its Birmingham colocation facility, targeting GPU cluster operators. The upgrade increases average rack density from 8kW to 40kW per rack.',
    source: 'Capacity Media',
    url: 'https://capacitymedia.com',
    published_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'news-006',
    company: 'Polar Data Facilities Nordic',
    category: 'hiring',
    headline: 'Polar Data expands UK procurement team ahead of London office opening',
    summary: 'Polar Data Facilities Nordic has posted 14 UK-based roles including a Head of UK Delivery, signalling serious intent to establish UK presence and potentially source MEP services locally.',
    source: 'LinkedIn Intelligence',
    url: 'https://linkedin.com',
    published_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'news-007',
    company: 'Titan Hosting Group',
    category: 'expansion',
    headline: 'Titan Hosting secures Tier III certification for upgraded Leeds facility',
    summary: 'Following a £7M MEP overhaul, Titan Hosting Group has achieved Uptime Institute Tier III certification for its Leeds South facility, unlocking enterprise contracts previously out of reach.',
    source: 'Uptime Institute',
    url: 'https://uptimeinstitute.com',
    published_at: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'news-008',
    company: 'ClearPath Datacentre Solutions',
    category: 'funding',
    headline: 'ClearPath raises £4M seed round to fund Bristol Tier III upgrade',
    summary: 'Bristol-based ClearPath Datacentre Solutions has raised £4M in seed funding to part-fund a full MEP upgrade from Tier II to Tier III compliance, targeting NHS and financial services tenants.',
    source: 'Tech South West',
    url: 'https://techsouthwest.co.uk',
    published_at: new Date(Date.now() - 11 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const DC_EVENTS_SEED = [
  {
    id: 'evt-001',
    name: 'DCD>Global London',
    date: '2025-11-19',
    location: 'ExCeL London, UK',
    type: 'conference',
    sector: 'data-centre',
    url: 'https://datacenterdynamics.com/events/dcdglobal-london/',
    description: "World's largest data centre conference. Critical for networking with DC developers, operators, and supply chain.",
    days_until: Math.ceil((new Date('2025-11-19').getTime() - Date.now()) / 86400000),
  },
  {
    id: 'evt-002',
    name: 'Datacloud Europe',
    date: '2025-06-10',
    location: 'Monaco',
    type: 'conference',
    sector: 'data-centre',
    url: 'https://www.datacloudgroup.com/dce/',
    description: 'Premier European data centre and cloud industry summit. High concentration of C-suite executives.',
    days_until: Math.ceil((new Date('2025-06-10').getTime() - Date.now()) / 86400000),
  },
  {
    id: 'evt-003',
    name: 'Gartner Data & Analytics Summit',
    date: '2025-09-22',
    location: 'London, UK',
    type: 'summit',
    sector: 'data-centre',
    url: 'https://www.gartner.com/en/conferences/emea/data-analytics-uk',
    description: 'Enterprise IT strategy summit. Strong representation from data centre buyers and CIOs.',
    days_until: Math.ceil((new Date('2025-09-22').getTime() - Date.now()) / 86400000),
  },
  {
    id: 'evt-004',
    name: 'UK Construction Week',
    date: '2025-10-07',
    location: 'NEC Birmingham, UK',
    type: 'exhibition',
    sector: 'construction',
    url: 'https://www.ukconstructionweek.com',
    description: 'UK\'s largest construction exhibition. Key for MEP subcontractors and data centre fit-out contractors.',
    days_until: Math.ceil((new Date('2025-10-07').getTime() - Date.now()) / 86400000),
  },
  {
    id: 'evt-005',
    name: 'Data Centre World',
    date: '2026-03-04',
    location: 'ExCeL London, UK',
    type: 'conference',
    sector: 'data-centre',
    url: 'https://www.datacentreworld.com',
    description: 'Leading technical conference for data centre professionals covering design, build, and operations.',
    days_until: Math.ceil((new Date('2026-03-04').getTime() - Date.now()) / 86400000),
  },
  {
    id: 'evt-006',
    name: 'Energy & Utilities Summit',
    date: '2025-05-14',
    location: 'Manchester, UK',
    type: 'summit',
    sector: 'energy',
    url: 'https://energyutilitiessummit.co.uk',
    description: 'Grid connection and renewable energy strategies for large power consumers including data centres.',
    days_until: Math.ceil((new Date('2025-05-14').getTime() - Date.now()) / 86400000),
  },
];

export const WIDGET_CONFIGS: WidgetConfig[] = [
  {
    id: 'diary-today',
    name: "Today's Diary",
    description: "Your schedule for today: calls, bid deadlines, follow-ups, and live signals",
    display: 'timeline',
    data_sources: ['align-calls-today', 'align-bid-deadlines', 'align-opportunities-followup', 'align-trigger-signals-today'],
    refresh_interval_minutes: 5,
    max_rows: 20,
    assistant_hints: [
      "Prioritise calls where a trigger signal has fired in the last 48 hours",
      "Flag any bid deadlines within 72 hours as urgent",
      "Surface top follow-up if opportunity has been stalled for more than 14 days",
    ],
    empty_message: "Nothing scheduled for today. Use this time to advance stalled opportunities.",
  },
  {
    id: 'tasks-today',
    name: "Today's Tasks",
    description: "Consolidated action list: overdue items, RFIs, compliance gaps, and pipeline actions",
    display: 'task-list',
    data_sources: ['open-rfis', 'compliance-items', 'bid-followups', 'opportunity-actions', 'scope-gaps', 'checklist-items'],
    refresh_interval_minutes: 10,
    max_rows: 30,
    assistant_hints: [
      "Lead with overdue items — do not bury them",
      "Group by urgency not category",
      "Inline completion should update backend immediately",
    ],
    empty_message: "All clear — no outstanding tasks. Excellent discipline.",
  },
  {
    id: 'newly-formed-dc-companies',
    name: 'New DC Projects',
    description: "Newly incorporated data centre companies and projects identified in the last 90 days",
    display: 'card-list',
    data_sources: ['align-accounts', 'align-intel-companies'],
    refresh_interval_minutes: 60,
    max_rows: 20,
    assistant_hints: [
      "Flag companies <30 days old with 'New' badge",
      "Highlight if any match existing pipeline accounts",
      "Prioritise by estimated project value descending",
    ],
    empty_message: "No new data centre companies detected in this period.",
    seed_data: DC_COMPANIES_SEED,
  },
  {
    id: 'dc-company-news',
    name: 'DC Intelligence Feed',
    description: "Latest news for data centre companies: expansions, funding, technology, and competitor moves",
    display: 'news-feed',
    data_sources: ['align-news-feed', 'align-signals'],
    refresh_interval_minutes: 30,
    max_rows: 15,
    assistant_hints: [
      "Expansion and funding news = highest commercial relevance",
      "Competitor activity = risk flag, escalate to BD",
      "Link news items to CRM accounts where match exists",
    ],
    empty_message: "No recent news for tracked data centre companies.",
    seed_data: DC_NEWS_SEED,
  },
  {
    id: 'top-n-by-category',
    name: 'Top Opportunities',
    description: "Ranked pipeline view: top opportunities, bids, and accounts by value or activity",
    display: 'ranked-table',
    data_sources: ['align-opportunities', 'align-bids', 'align-accounts'],
    refresh_interval_minutes: 15,
    max_rows: 10,
    assistant_hints: [
      "Surface stalled opportunities (no movement >14 days) with amber flag",
      "Highlight deals in negotiation or preferred bidder stage",
      "Show both value and strategic leverage score where available",
    ],
    empty_message: "No pipeline data available. Add your first opportunity to get started.",
  },
  {
    id: 'upcoming-sector-events',
    name: 'Sector Events',
    description: "Upcoming data centre, construction, and energy industry events",
    display: 'timeline',
    data_sources: ['align-trigger-signals-today', 'external-events-feed'],
    refresh_interval_minutes: 1440,
    max_rows: 12,
    assistant_hints: [
      "Highlight next event within 30 days",
      "Flag events where a target account is likely to attend",
      "Group by month for clarity",
    ],
    empty_message: "No upcoming events in the selected timeframe.",
    seed_data: DC_EVENTS_SEED,
  },
];
